package com.peihua8858.badgeview.ksp

import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate
import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSFile
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.TypeSpec
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.text.MessageFormat
import java.text.SimpleDateFormat
import java.util.Date
import kotlin.collections.component1
import kotlin.collections.component2
import kotlin.sequences.partition

class KspBadgeProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return KspBadgeProcessor(environment)
    }
}

class KspBadgeProcessor(private val environment: SymbolProcessorEnvironment) : SymbolProcessor {
    companion object {
        private const val CLASS_JAVA_DOC =
            "Generated by Badge-Processor. Do not edit it!\n" +
                    "@author dingpeihua\n" +
                    "@date %s\n" +
                    "@version 1.0\n"
        private const val PACKAGE_NAME = "com.fz.badgeview"
        private const val CLASS_PREFIX = "Badge"
        private const val ATTRS_XML_PATH: String = "badgeViewResValues.xml"
        private const val RESOURCES_TAG: String = "<resources>"
        private const val RESOURCES_END_TAG: String = "</resources>"
        private const val ATTRS_XML_TEMPLATE = "<declare-styleable name=\"{0}\">\n" +
                "        <attr name=\"badge_text\" />\n" +
                "        <attr name=\"badge_bgColor\" />\n" +
                "        <attr name=\"badge_textColor\" />\n" +
                "        <attr name=\"badge_textSize\" />\n" +
                "        <attr name=\"badge_verticalMargin\" />\n" +
                "        <attr name=\"badge_horizontalMargin\" />\n" +
                "        <attr name=\"badge_padding\" />\n" +
                "        <attr name=\"badge_gravity\" />\n" +
                "        <attr name=\"badge_draggable\" />\n" +
                "        <attr name=\"badge_isResumeTravel\" />\n" +
                "        <attr name=\"badge_borderWidth\" />\n" +
                "        <attr name=\"badge_borderColor\" />\n" +
                "        <attr name=\"badge_dragExtra\" />\n" +
                "        </declare-styleable>"
    }

    private val mBadgeMethodImpl: KotlinBadgeMethodImpl = KotlinBadgeMethodImpl(PACKAGE_NAME, this)
    private var mResolver: Resolver? = null
    private val symbolsVisitor = HashSet<String>()
    fun getClassDeclarationByName(name: String): KSClassDeclaration? = mResolver?.getClassDeclarationByName(name)
    override fun process(resolver: Resolver): List<KSAnnotated> {
        printMessage("====================================== BadgeProcessor process START ======================================")
        this.mResolver = resolver
        val result = resolver.classes
        return try {
            processChecked(resolver, result.first)
            result.first
        } catch (e: Throwable) {
            printErrorMessage("build error:" + e.stackTraceToString())
            result.second
        }
    }

    @Suppress("SimpleDateFormat")
    private fun processChecked(resolver: Resolver, validSymbols: List<KSClassDeclaration>) {
        if (validSymbols.isNotEmpty()) {
            printMessage("生成 " + validSymbols.size + " 个")
            printMessage("Target classes from annotation: ${validSymbols.joinToString { it.simpleName.asString() }}")
            val classNames = mutableListOf<String>()
            val date = SimpleDateFormat("yyyy/M/dd HH:mm")
            validSymbols.forEach { targetClass ->
                val superPackageName = targetClass.packageName.asString()
                val superClassName = targetClass.simpleName.asString()
                val className = CLASS_PREFIX + superClassName
                classNames.add(className)
                printMessage("superPackageName ====> $superPackageName,superClassName: $superClassName")
                date.format(Date())
                val javaDoc = String.format(CLASS_JAVA_DOC, date)
                val typeBuilder = TypeSpec.classBuilder(className)
                    .addKdoc(javaDoc)
                    .addModifiers(KModifier.PUBLIC)
                    .superclass(ClassName(superPackageName, superClassName))
                    .addSuperinterface(ClassName(PACKAGE_NAME, "IBadgeFeature"))
                    .addProperty(
                        "mBadgeViewHelper",
                        ClassName(PACKAGE_NAME, "BadgeViewHelper"),
                        KModifier.PRIVATE
                    )
                generateMethod(typeBuilder, targetClass)
                val file = FileSpec.builder(PACKAGE_NAME, className)
                    .addType(typeBuilder.build())
                    .build()
                writeFile(file, resolver.getAllFiles().toList())
            }
            // 路径例如: /xxx/app/build/generated/source/kapt/debug
            val kspGenDir = resolver.kspGenDir
            printMessage("kaptGenDir>>>kaptPath:${kspGenDir}")
            val resOutDir = kspGenDir.resolve("values")
            val filePath = Files.createDirectories(resOutDir)
            val attrsFile = resOutDir.resolve(ATTRS_XML_PATH)
            printMessage("开始生成 attrs.xml, 生成的目录：$filePath")
            generateAttrsXml(classNames).let { content ->
                try {
                    Files.write(attrsFile, content.toString().toByteArray(StandardCharsets.UTF_8))
                    printMessage("生成 attrs.xml 结束")
                } catch (e: Exception) {
                    printMessage(
                        "生成 attrs.xml 错误,生成的内容：$content\n" +
                                e.stackTraceToString()
                    )
                }
            }
            printMessage("====================================== BadgeProcessor process END ======================================")
        }
    }

    private fun generateAttrsXml(classNames: List<String>): String {
        val content = StringBuilder()
        content.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
        content.append("\n")
        content.append(RESOURCES_TAG)
        content.append("\n")
        classNames.forEach {
            content.append(MessageFormat.format(ATTRS_XML_TEMPLATE, it))
            content.append("\n")
        }
        content.append(RESOURCES_END_TAG)
        return content.toString()
    }

    private val Resolver.classes: Pair<List<KSClassDeclaration>, List<KSAnnotated>>
        get() {
            val classesStrs = environment.options["classes"]
            printMessage("classes>>>classesStrs:${classesStrs}")
            val result = mutableListOf<KSClassDeclaration>()
            if (!classesStrs.isNullOrEmpty()) {
                val invalidSymbols = mutableListOf<KSAnnotated>()
                val classes = classesStrs.split("|").map { it.trim() }
                    .filter { it.isNotEmpty() }
                    .distinct()
                classes.forEach {
                    val clazz = getClassDeclarationByName(it)
                    if (clazz != null) {
                        if (symbolsVisitor.contains(it)) {
                            invalidSymbols.add(clazz)
                            return@forEach
                        }
                        result.add(clazz)
                        symbolsVisitor.add(it)
                    }
                }
                printMessage("classes>>>result:${result}")
                return result to invalidSymbols
            } else {
                val symbols = getSymbolsWithAnnotation("com.fz.badgeview.annotation.BadgeView")
                val (validSymbols, invalidSymbols) = symbols.partition { it.validate() }.toList()
                printMessage("classes>>>symbols:${symbols}")
                val result = mutableListOf<KSClassDeclaration>()
                validSymbols.filterIsInstance<KSClassDeclaration>().forEach { classDeclaration ->
                    val badgeAnnotation = classDeclaration.annotations.find { it.shortName.asString() == "BadgeView" }
                    val targetClasses = extractTargetClassesFromAnnotation(badgeAnnotation)
                    result.addAll(targetClasses)
                }
                return result to invalidSymbols
            }
        }

    @OptIn(KspExperimental::class)
    private val Resolver.kspGenDir: Path
        get() {
            val path = Paths.get("build/generated/res/resValues");
            val file = getAllFiles().first()
            val filePath = file.filePath
            printMessage("kspGenDir>>>file:${filePath}")
            val moduleName = getModuleName().asString()
            printMessage("kspGenDir>>>moduleName:${moduleName}")
            val (name, buildType) = moduleName.split("_")
            printMessage("kspGenDir>>>name:${name},buildType:$buildType")
            var moduleIndex = filePath.indexOf(name)
            if (moduleIndex == -1) {
                moduleIndex = filePath.length
            }
            val outDir = Paths.get(filePath.substring(0, moduleIndex)).resolve(name)
            printMessage("kspGenDir>>>outDir:${outDir}")
            return outDir.resolve(path).resolve(buildType)
        }

    /**
     * 从 BadgeView 注解中提取 values 参数包含的所有目标类
     */
    private fun extractTargetClassesFromAnnotation(annotation: KSAnnotation?): List<KSClassDeclaration> {
        if (annotation == null) {
            return emptyList()
        }
        val valuesArgument = annotation.arguments.find { it.name?.asString() == "values" }?.value
        if (valuesArgument == null || valuesArgument !is List<*>) {
            return emptyList()
        }

        return valuesArgument.mapNotNull { value ->
            if (value is KSType) {
                value.declaration as? KSClassDeclaration
            } else {
                null
            }
        }
    }

    /**
     * 生成文件
     * sources =resolver.getAllFiles().toList()
     */
    private fun writeFile(file: FileSpec, sources: List<KSFile>) {
        try {
            environment.codeGenerator
                .createNewFile(
                    Dependencies(aggregating = true, sources = sources.toTypedArray()),
                    file.packageName,
                    file.name,
                )
                .writer()
                .use { file.writeTo(it) }
        } catch (e: FileAlreadyExistsException) {
            printWarnMessage(">>>>>>file already exists, skip: ${file.packageName}.${file.name},${e.message}")
        }
    }

    private fun generateMethod(typeBuilder: TypeSpec.Builder, classDeclaration: KSClassDeclaration) {
        mBadgeMethodImpl.apply {
            val methods = this.javaClass.declaredMethods
            printMessage("generateMethod>>>> methods.size: ${methods.size}")
            for (method in methods) {
                val parameters = method.parameters
                if (parameters.size == 2) {
                    method.invoke(this, typeBuilder, classDeclaration)
                } else {
                    if (method.name != "dispatchDraw") {
                        method.invoke(this, typeBuilder)
                    }
                }
            }
        }
    }

    fun printMessage(msg: String) {
        environment.printMessage(msg)
    }

    fun SymbolProcessorEnvironment.printMessage(msg: String) {
        logger.info(msg)
    }

    fun printWarnMessage(msg: String) {
        environment.printWarnMessage(msg)
    }

    /**
     * 打印错误
     */
    fun SymbolProcessorEnvironment.printWarnMessage(msg: String) {
        logger.warn(msg)
    }

    fun printErrorMessage(msg: String) {
        environment.printErrorMessage(msg)
    }

    /**
     * 打印错误
     */
    fun SymbolProcessorEnvironment.printErrorMessage(msg: String) {
        logger.error(msg)
    }
}