package com.fz.badgeview.compiler

import com.fz.badgeview.annotation.BadgeView
import com.google.auto.service.AutoService
import com.squareup.javapoet.ClassName
import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.TypeSpec
import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.text.MessageFormat
import java.text.SimpleDateFormat
import java.util.Date
import javax.annotation.processing.AbstractProcessor
import javax.annotation.processing.Filer
import javax.annotation.processing.Messager
import javax.annotation.processing.ProcessingEnvironment
import javax.annotation.processing.Processor
import javax.annotation.processing.RoundEnvironment
import javax.lang.model.element.Element
import javax.lang.model.element.ElementKind
import javax.lang.model.element.Modifier
import javax.lang.model.element.TypeElement
import javax.lang.model.type.DeclaredType
import javax.lang.model.type.MirroredTypesException
import javax.tools.Diagnostic
import javax.tools.StandardLocation

@Suppress("MISSING_DEPENDENCY_CLASS_IN_EXPRESSION_TYPE")
@AutoService(Processor::class)
class BadgeProcessor : AbstractProcessor() {

    companion object {
        private const val CLASS_JAVA_DOC =
            "Generated by Badge-Processor. Do not edit it!\n" +
                    "@author dingpeihua\n" +
                    "@date %s\n" +
                    "@version 1.0\n"
        private const val PACKAGE_NAME = "com.fz.badgeview"
        private const val CLASS_PREFIX = "Badge"
        private const val ATTRS_XML_PATH: String = "badgeViewResValues.xml"
        private const val RESOURCES_TAG: String = "<resources>"
        private const val RESOURCES_END_TAG: String = "</resources>"
        private const val ATTRS_XML_TEMPLATE = "<declare-styleable name=\"{0}\">\n" +
                "        <attr name=\"badge_text\" />\n" +
                "        <attr name=\"badge_bgColor\" />\n" +
                "        <attr name=\"badge_textColor\" />\n" +
                "        <attr name=\"badge_textSize\" />\n" +
                "        <attr name=\"badge_verticalMargin\" />\n" +
                "        <attr name=\"badge_horizontalMargin\" />\n" +
                "        <attr name=\"badge_padding\" />\n" +
                "        <attr name=\"badge_gravity\" />\n" +
                "        <attr name=\"badge_draggable\" />\n" +
                "        <attr name=\"badge_isResumeTravel\" />\n" +
                "        <attr name=\"badge_borderWidth\" />\n" +
                "        <attr name=\"badge_borderColor\" />\n" +
                "        <attr name=\"badge_dragExtra\" />\n" +
                "        </declare-styleable>"
    }

    private var mFileUtils: Filer? = null
    private var mMessager: Messager? = null
    private var mBadgeableMethod: IBadgeMethod? = null

    @Synchronized
    override fun init(processingEnvironment: ProcessingEnvironment?) {
        super.init(processingEnvironment)
        mFileUtils = processingEnv.filer
        mMessager = processingEnv.messager
        mBadgeableMethod = BadgeMethodImpl(PACKAGE_NAME, processingEnv)
    }

    /**
     * 告知 Processor 哪些注解需要处理
     *
     * @return 返回一个 Set 集合，集合内容为自定义注解的包名+类名
     */
    override fun getSupportedAnnotationTypes(): Set<String> {
        val annotationTypes: MutableSet<String> = LinkedHashSet()
        annotationTypes.add(BadgeView::class.java.canonicalName)
        return annotationTypes
    }

    override fun getSupportedOptions(): Set<String?>? {
        return super.getSupportedOptions()
    }
    /**
     * 所有的注解处理都是从这个方法开始的，当 APT 找到所有需要处理的注解后，会回调这个方法。当没有属于该 Processor 处理的注解被使用时，不会回调该方法
     *
     * @param set              所有的由该 Processor 处理，并待处理的 Annotations「属于该 Processor 处理的注解，但并未被使用，不存在与这个集合里」
     * @param roundEnvironment 表示当前或是之前的运行环境，可以通过该对象查找到注解
     * @return 表示这组 Annotation 是否被这个 Processor 消费，如果消费「返回 true」后续子的 Processor 不会再对这组 Annotation 进行处理
     */
    override fun process(set: Set<TypeElement?>?, roundEnvironment: RoundEnvironment): Boolean {
        val result = roundEnvironment.classes
        if (result.isEmpty()) {
            return true
        }
        printMessage(Diagnostic.Kind.NOTE, "====================== BadgeProcessor process START ======================")
        try {
            generate(result)
        } catch (e: IllegalAccessException) {
            e.printStackTrace()
        } catch (e: IOException) {
            printMessage(Diagnostic.Kind.ERROR, "Exception occurred when generating class file.")
            e.printStackTrace()
        }
        printMessage(Diagnostic.Kind.NOTE, "====================== BadgeProcessor process END ======================")
        return true
    }

    @Throws(IllegalAccessException::class, IOException::class)
    private fun generate(viewClassSet: List<String>) {
        processingEnv?.apply {
            printMessage(Diagnostic.Kind.NOTE, "生成 " + viewClassSet.size + " 个")
            val classNames = mutableListOf<String>()
            for (clazz in viewClassSet) {
                val lastDotIndex = clazz.lastIndexOf(".")
                val superPackageName = clazz.substring(0, lastDotIndex)
                val superClassName = clazz.substring(lastDotIndex + 1)
                val className = CLASS_PREFIX + superClassName
                classNames.add(className)
                printMessage(Diagnostic.Kind.NOTE, "$clazz ====> $className")
                val date = SimpleDateFormat("yyyy/M/dd HH:mm").format(Date())
                val javaDoc = String.format(CLASS_JAVA_DOC, date)
                val typeBuilder = TypeSpec.classBuilder(className)
                    .addJavadoc(javaDoc)
                    .addModifiers(Modifier.PUBLIC)
                    .superclass(ClassName.get(superPackageName, superClassName))
                    .addSuperinterface(ClassName.get(PACKAGE_NAME, "IBadgeFeature"))
                    .addField(
                        ClassName.get(PACKAGE_NAME, "BadgeViewHelper"),
                        "mBadgeViewHelper",
                        Modifier.PRIVATE
                    )
                generateMethod(typeBuilder, clazz)
                val javaFile = JavaFile.builder(PACKAGE_NAME, typeBuilder.build()).build()
                javaFile.writeTo(mFileUtils)
            }
            // 路径例如: /xxx/app/build/generated/source/kapt/debug
            val kaptPath = processingEnv.kaptGenDir
            printMessage(Diagnostic.Kind.NOTE, "kaptGenDir>>>kaptPath:${kaptPath}")
            val projectDir = kaptPath.parent.parent.parent
            val resOutDir = projectDir.resolve("res").resolve("resValues").resolve(kaptPath.fileName).resolve("values")
            val filePath = Files.createDirectories(resOutDir)
            val attrsFile = resOutDir.resolve(ATTRS_XML_PATH)
            printMessage(Diagnostic.Kind.NOTE, "开始生成 attrs.xml, 生成的目录：$filePath")
            generateAttrsXml(classNames).let { content ->
                try {
                    Files.write(attrsFile, content.toString().toByteArray(StandardCharsets.UTF_8))
                    printMessage(Diagnostic.Kind.NOTE, "生成 attrs.xml 结束")
                } catch (e: Exception) {
                    printMessage(
                        Diagnostic.Kind.NOTE, "生成 attrs.xml 错误,生成的内容：$content\n" +
                                e.stackTraceToString()
                    )
                }
            }
        }
    }
    private val symbolsVisitor = HashSet<String>()
    private val RoundEnvironment.classes: List<String>
        get() {
            val classesStrs = processingEnv.options["classes"]
            printMessage("classes>>>classesStrs:${classesStrs}")
            val result = mutableListOf<String>()
            if (!classesStrs.isNullOrEmpty()) {
                val classes = classesStrs.split("|").map { it.trim() }
                    .filter { it.isNotEmpty() }
                    .distinct()
                classes.forEach {
                    if (it.isNotEmpty()) {
                        if (symbolsVisitor.contains(it)) {
                            return@forEach
                        }
                        result.add(it)
                        symbolsVisitor.add(it)
                    }
                }
                printMessage("classes>>>result:${result}")
                return result
            } else {
                val elements: Set<Element>? = getElementsAnnotatedWith(BadgeView::class.java)
                if (elements.isNullOrEmpty()) {
                    return emptyList()
                }
                elements.forEach {
                    checkAnnotationValid(it, BadgeView::class.java)
                    val classElement = it as TypeElement
                    // 获取该注解的值
                    val badgeAnnotation = classElement.getAnnotation(BadgeView::class.java)
                    try {
                        badgeAnnotation.values
                    } catch (e: MirroredTypesException) {
                        val typeMirrors = e.typeMirrors
                        for (typeMirror in typeMirrors) {
                            val classTypeMirror = typeMirror as DeclaredType
                            val classTypeElement = classTypeMirror.asElement() as TypeElement
                            val qualifiedName = classTypeElement.qualifiedName.toString()
                            result.add(qualifiedName)
                        }
                    }
                }
                return result
            }
        }
    private val ProcessingEnvironment.kaptGenDir: Path
        get() {
            val kaptOut = options["kapt.kotlin.generated"]
            if (kaptOut != null) {
                val path = Paths.get(kaptOut)
                // 路径例如: /xxx/app/build/generated/source/kapt/debug
                printMessage(Diagnostic.Kind.NOTE, "kaptGenDir>>>kaptOut:${path}")
                return path
            }
            val foPath = filer.getResource(StandardLocation.SOURCE_OUTPUT, "", "res")
            printMessage(Diagnostic.Kind.NOTE, "kaptGenDir>>>SOURCE_OUTPUT:${foPath.name}")
            return Paths.get(foPath.name).parent
        }

    private fun generateAttrsXml(classNames: List<String>): String {
        val content = StringBuilder()
        content.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
        content.append("\n")
        content.append(RESOURCES_TAG);
        content.append("\n")
        classNames.forEach {
            content.append(MessageFormat.format(ATTRS_XML_TEMPLATE, it))
            content.append("\n")
        }
        content.append(RESOURCES_END_TAG)
        return content.toString()
    }

    private fun generateMethod(typeBuilder: TypeSpec.Builder, clazz: String) {
        mBadgeableMethod?.apply {
            val methods = this.javaClass.declaredMethods
            for (method in methods) {
                val parameters = method.parameters
                if (parameters.size == 2) {
                    method.invoke(this, typeBuilder, clazz)
                } else {
                    if (method.name != "dispatchDraw") {
                        method.invoke(this, typeBuilder)
                    }
                }
            }
        }

    }

    private fun checkAnnotationValid(annotatedElement: Element, clazz: Class<*>): Boolean {
        if (annotatedElement.kind != ElementKind.CLASS) {
            error(annotatedElement, "%s must be declared on class.", clazz.simpleName)
            return false
        }
        if (annotatedElement.modifiers.contains(Modifier.PRIVATE)) {
            error(
                annotatedElement,
                "%s must can not be private.",
                (annotatedElement as TypeElement).qualifiedName
            )
            return false
        }
        return true
    }

    private fun error(element: Element, message: String, vararg args: Any) {
        var message1: String = message
        if (args.isNotEmpty()) {
            message1 = String.format(message1, *args)
        }
        mMessager?.printMessage(Diagnostic.Kind.ERROR, message1, element)
    }

    fun printMessage(kind: Diagnostic.Kind, msg: CharSequence) {
        processingEnv?.printMessage(kind, msg)
    }

    fun ProcessingEnvironment.printMessage(kind: Diagnostic.Kind, msg: CharSequence) {
        messager?.printMessage(kind, msg)
    }

    fun printMessage(msg: CharSequence) {
        processingEnv?.printMessage(msg)
    }

    fun ProcessingEnvironment.printMessage(msg: CharSequence) {
        messager?.printMessage(Diagnostic.Kind.NOTE, msg)
    }
}