package com.fz.badgeview.compiler

import com.fz.badgeview.annotation.BadgeView
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.validate
import com.google.devtools.ksp.getClassDeclarationByName
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import java.text.SimpleDateFormat
import java.util.Date

class KspBadgeProcessor(private val environment: SymbolProcessorEnvironment) : SymbolProcessor {
    private val CLASS_JAVA_DOC =
        "Generated by Badge-Processor. Do not edit it!\n" +
                "@author dingpeihua\n" +
                "@date %s\n" +
                "@version 1.0\n"

    private val PACKAGE_NAME = "com.fz.badgeview"
    private val CLASS_PREFIX = "Badge"
    private val mBadgeMethodImpl: KotlinBadgeMethodImpl = KotlinBadgeMethodImpl(PACKAGE_NAME, this)
    private var mResolver: Resolver? = null
    fun getClassDeclarationByName(name: String): KSClassDeclaration? = mResolver?.getClassDeclarationByName(name)
    override fun process(resolver: Resolver): List<KSAnnotated> {
        println("Found symbols, process: >>>>>>>>>>>>>>")
        this.mResolver = resolver
        val symbols = resolver.getSymbolsWithAnnotation("com.fz.badgeview.annotation.BadgeView")
        val (validSymbols, invalidSymbols) = symbols.partition { it.validate() }.toList()
        return try {
            processChecked(resolver, symbols, validSymbols, invalidSymbols)
        } catch (e: Exception) {
            environment.logger.error(e.message ?: "")
            invalidSymbols
        }
    }

    @Suppress("SimpleDateFormat")
    private fun processChecked(
        resolver: Resolver,
        symbols: Sequence<KSAnnotated>,
        validSymbols: List<KSAnnotated>,
        invalidSymbols: List<KSAnnotated>,
    ): List<KSAnnotated> {
        val logger = environment.logger
        println("Found symbols, symbols: $symbols")
        logger.info("Found symbols, symbols: $symbols")
        logger.info("====================================== BadgeProcessor process START ======================================")
        println("====================================== BadgeProcessor process START ======================================")
        if (validSymbols.isNotEmpty()) {
            logger.info("生成 " + validSymbols.size + " 个")
            validSymbols.filterIsInstance<KSClassDeclaration>()
                .forEach { classDeclaration ->
                    // 获取注解参数中的 values 数组
                    val badgeAnnotation = classDeclaration.annotations.find { it.shortName.asString() == "BadgeView"}
                    val targetClasses = if (badgeAnnotation != null) {
                        extractTargetClassesFromAnnotation(badgeAnnotation)
                    } else {
                        emptyList()
                    }
                    targetClasses.forEach { targetClass ->
                        val superPackageName = targetClass.packageName.asString()
                        val superClassName = targetClass.simpleName.asString()
                        val className = CLASS_PREFIX + superClassName
                        logger.info("$superPackageName ====> $superPackageName,superClassName: $superClassName")
                        logger.info("Target classes from annotation: ${targetClasses.joinToString { it.simpleName.asString() }}")
                        val date = SimpleDateFormat("yyyy/M/dd HH:mm").format(Date())
                        val javaDoc = String.format(CLASS_JAVA_DOC, date)
                        val typeBuilder = TypeSpec.classBuilder(className)
                            .addKdoc(javaDoc)
                            .addModifiers(KModifier.PUBLIC)
                            .superclass(ClassName(superPackageName, superClassName))
                            .addSuperinterface(ClassName(PACKAGE_NAME, "IBadgeFeature"))
                            .addProperty(
                                "mBadgeViewHelper",
                                ClassName(PACKAGE_NAME, "BadgeViewHelper"),
                                KModifier.PRIVATE
                            )
                        generateMethod(typeBuilder, targetClass)
                        val file = FileSpec.builder(PACKAGE_NAME, className)
                            .addType(typeBuilder.build())
                            .build()
                        writeFile(file, resolver.getAllFiles().toList())
                    }

                }
        }
        logger.info("====================================== BadgeProcessor process END ======================================")
        return invalidSymbols
    }
    
    /**
     * 从 BadgeView 注解中提取 values 参数包含的所有目标类
     */
    private fun extractTargetClassesFromAnnotation(annotation: KSAnnotation): List<KSClassDeclaration> {
        val valuesArgument = annotation.arguments.find { it.name?.asString() == "values" }?.value
        if (valuesArgument == null || valuesArgument !is List<*>) {
            return emptyList()
        }
        
        return valuesArgument.mapNotNull { value ->
            if (value is KSType) {
                value.declaration as? KSClassDeclaration
            } else {
                null
            }
        }
    }
    private fun writeFile(file: FileSpec, sources: List<KSFile>) {
        environment.codeGenerator
            .createNewFile(
                Dependencies(aggregating = false, sources = sources.toTypedArray()),
                file.packageName,
                file.name,
            )
            .writer()
            .use { file.writeTo(it) }

        environment.logger.info("Wrote file: $file")
    }
    private fun generateMethod(typeBuilder: TypeSpec.Builder, classDeclaration: KSClassDeclaration) {
        mBadgeMethodImpl.apply {
            val methods = this.javaClass.declaredMethods
            environment.logger.info("generateMethod>>>> methods.size: ${methods.size}")
            for (method in methods) {
                val parameters = method.parameters
                if (parameters.size == 2) {
                    method.invoke(this, typeBuilder, classDeclaration)
                } else {
                    if (method.name!="dispatchDraw") {
                        method.invoke(this, typeBuilder)
                    }
                }
            }
        }

    }
}