plugins {
    id 'java-library'
    id 'kotlin'
    id 'maven-publish'
}
kotlin { jvmToolchain { languageVersion.set(JavaLanguageVersion.of(17)) } }
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
dependencies {
    compileOnly 'com.google.android:android:4.1.1.4'
}
group = 'com.github.peihua8858'
afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            release(MavenPublication) {
                groupId = 'com.github.peihua8858'
                artifactId = 'annotation'
                version = '1.0.0'
                from(components.getByName("java"))
            }
        }
    }
}
//apply from: "push_local_maven.gradle"